### PR TITLE
Suggestions for L1V4 cover page

### PR DESCRIPTION
**Pull request by jonrkarr**
- More emphasis on the need for a common format to facilitate collaboration in modeling/simulation
- Less emphasis on MIASE
- Change description of MIASE from "proposes" to "outlines"
- Brief summary of achievements of prior versions of SED-ML
- More emphasis on innovations introduced in L1V4 and simultaneous expansion of the software ecosystem. I personally feel that the concretization of SED-ML and validation rules are key. These are critical to the vision of being able to exchange SED-ML between investigators/tools.

### CODE REVIEW

**Review by luciansmith — COMMENTED** [review]
Edited!  I generally kept the changes, but made some changes to hopefully make it flow better, and restored the original opening statement, which I felt was a better introduction to the spec.

**Comment by luciansmith** [comment]
For some reason, I can't request you back as a re-reviewer?  Anyway, happy to take further suggestions.

**Comment by jonrkarr** [comment]
Looks good. I would just suggest rephrasing the first sentence to be a little more different from the first sentence of the L1V3 paper.

L1 V3
> The creation of computational simulation experiments to inform modern biological research poses challenges to reproduce, annotate, archive, and share such experiments.

L1 V4 (current version)
> The use of computational simulation experiments to inform modern biological research creates new challenges to annotate, archive, share and reproduce such experiments.

**Comment by luciansmith** [comment]
Done!

**Pull request merged**
